### ISSUE TITLE
Could a Nintendo switch be cleared out of electronics and have a single board computer inside to run it and connect to joycons

### ISSUE THREAD

**Issue by superpotato9** [dekuNukem/Nintendo_Switch_Reverse_Engineering#120]
My question is could I get a (preferably broken) Nintendo switch and clear out its pcb and other internal components and put in a pi seems simple but would it be possible to connect to the joy cons via the physical connectors especially for charging and using a joysticks/ buttons for interacting with the pi ? I would guess some driver board would need to be made by me

**Comment by TomEke** [comment]
I thought about this recently too, using the newer Raspberry Pi 4 Compute Module. 

According to #71 the LCD uses a 4-lane DSI, which the CM does support (but the regular Pis do not). I can't find any information on the digitizer pin-out. I think it also has two different pin-outs depending on the model too. 

The joy-cons for charging should be easy just by supplying it with 5V. Data may be harder, but you could always just connect it over Bluetooth even when attached.
