### ISSUE TITLE
CRC info

### ISSUE THREAD

**Issue by ewalt1** [dekuNukem/Nintendo_Switch_Reverse_Engineering#5]
Just took a stab at the checksum. Based on the data provided it appears to be a CRC8 with polynomial x8 + x7 + x3 + x2 + 1 (110001101) computed over bytes 5 through 11.
[switch_checksum.py.zip](https://github.com/dekuNukem/Nintendo_Switch_Reverse_Engineering/files/843548/switch_checksum.py.zip)

**Comment by dekuNukem** [comment]
Thank you so much for the contribution, I've added it to the repo.
