### ISSUE TITLE
Controller stick interface (5-wire flexible PCB)

### ISSUE THREAD

**Issue by hattesen** [dekuNukem/Nintendo_Switch_Reverse_Engineering#69]
Do you have any information of the pinout (and interface) of the 5-wire flexible PCB that connects the control stick with the controller PCB?

I would guess something like:

- GND
- VCC
- X (analog)
- Y (analog)
- Switch (short to GND)

![image](https://user-images.githubusercontent.com/3527219/50574180-523d5800-0de3-11e9-859d-1a195c61609d.png)

![image](https://user-images.githubusercontent.com/3527219/50574188-7c8f1580-0de3-11e9-97ec-bb9bbe9e721a.png)

**Comment by patriot1889** [comment]
![naisog4](https://user-images.githubusercontent.com/2946724/50648657-b55df480-0f73-11e9-9d5a-8845eab28f74.jpg)

I found this on a different website.

**Comment by benjaminaigner** [comment]
Do you maybe know if the X/Y axis are done via a resistor divider for up/down and left/right?
If yes & if my Ali order finally arrives, I can publish an Arduino Joycon Stick to Mouse interface :-)

THX @all for all the specs in this repository!
